---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: malitda-azure
  namespace: malitda
spec:
  encryptedData:
    AZURE_SPEECH_KEY: AgB1/n/zYxkUxSvKDUX2sCB5Kg7AHPWdcXViaLeOTuApE14yuAE4CzaSWv9lE4M+hRoeulVsy99pkcXgs2o+C7rSxrwgpiox2IYOqqJId5rWD3fRF0YvxXgHJB3K7+i6maZLzLiLdalH2XnWCZ2kNrQi6JLejXHCuQjUS5b6k/6zeJXEChFgse785lKe4NUlKnNlYsnD7mvZqzL5wwEKCBqS16BIQNqZrFcAvuB0SIOld2r2K7w45MtJeNKdS9NfN2gVGFt+/acEjVExvstA+aTSe9j4SBlpZBZY9uln6DkKHTWGDbTN446/W6prrx4w5jMmcGvs8avet/b4kuCfYhlVN1UrWDDpvMOTq7U1vbgVQQRsDW3W8OHNab1w5V6oJoAD4Zz8l66IPy5FO9aXBdFlAyMfan/NlnN0tMhf3vG75WvRQ1iuRS8lfKj3TrzhcDFYM/9FgPzSXokPByKk2YCNupd1VXKCiRQ/fEjV9qHL5Q0WW/0A+rh4OwDO1mcpOO0TKaQTKhRr6S96um595mupeZOHpKcX2B8nJ1hT5DQi9cBjLWtwAeGTwu3CWFW2cfcKgUIIhqh4rF8wPIhzsq0FkR8vjh7D3hvVawzzmCbG2ANTz8pS9lgvCPyWTrRY49tUJUxwWH2bL4+8hnGkqYlabICHK9b605TNFNe9LyV4i1Vtklv22x4yDjVEotjLY4H4C2U2uo3APHHWYy9Nw2+AFVrd49FgfMV4Za2D/2Jp1rnibmajwkZ9vu3caRMASQjcy7Obv5IaHL08vJYGqzQgU+siMAx7H/bRPellnK74DUCxFa4=
  template:
    metadata:
      name: malitda-azure
      namespace: malitda
    type: Opaque
