---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: malitda-gemini
  namespace: malitda
spec:
  encryptedData:
    GEMINI_API_KEY: AgAoAjwEbPxfMK5QVci4aaBvB5TrdBISPQI8bCWiZ8Ig4W9jWITa07R7ihNCwUwpk8uCEY0tpOLiboYAzMHNASS8tGycgFc2h+pgtSpMHADwqxg6uUTq9XQereA5uHIQZEwxQl+xDfpsAqEstglkkLoW3WrK+of3UVJS50djrMvV4ga4dsxa7JNA/CWkgZctyYgYsPWdGWwtauPZQ7b7J0Pyj51UThz3kOsvs5yfs5buQ5ttN85GQs085JA5eBoOri10fhnTXzOScG/qB0P/G8uiuOS3Tw97Wfc18JM3o9O/NshdeX8zw4GRl/43UsSOiBN18hk67VubxLc4B7rRutQWI6G6Ubbuu/EkJLZs+tgkxqABBeugJ8AQU0RKEbsUJy1QS7d0qM+QuX8HrSFNstbYLl0EuJmB+6JUait3JB0yPiqgSJ1mqS+ljXThTZ+tdbNoO1LxbupMHuwTFpifuDzkNz67myWCFSHDKjGF9U6l57PpJCsqyXAoDUImHdk7vZaX0QwqWaMehPNBtqzbROcObIguB3j6aScRLpZIJQobcOPE++uJ04xlLetyrknOan6AlLispJ267UdCSPAGCtqbbsCqe2N6gf2N+dmtK5xSOsagUs4QjvzyvtS8NHV1LtIThc6d80IS/Z+xTUAJWuxOV0ApYFlwAPkY82Gj016BDCBQRGvhAGcOe31K0MH5FrN5YfN+mUe7gRL3ubCkySBjXIYHwHHXMhS8gRorZNJCAqGaACEMEco=
  template:
    metadata:
      name: malitda-gemini
      namespace: malitda
    type: Opaque
