---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-aws-secret
  namespace: tobehealthy
spec:
  encryptedData:
    AWS_S3_ACCESS_KEY: AgBe8FiBtIrgmh7M7AEAUqw53eYT/Fe8hsJru1PIqAnId5pbBfuCEhamSUVLPu8A4lspvpQzNpbni7wiZF8otwI2lud8G6yYgqb/ayHdMb2ScVn98ywoMqe/QWmBIYSJNaYMfb9Oe6uNaCHOQLlP71reu84tzNsd6phMNqmcLWgq3wM2HenPhzbEdNWLpaX7qKSIs6fn45peD21ZmK9g/aoYqZjJFeEOFiZDXBwd7YUQAzPf8EP3XsAMeYNEzZddpU70+upyIv/rOhDqD2cihKxiy8QnvJAAOI/acTkLrPiP7ypcO7OeouQTYhtI/LwxGbqH3NocX87yohegpkq2TvbuxJe664KxUxyrGdTK2r+4tjLbSFoAWrq45dWJRxqI0Vr39Xg+8x7Bfp9gmFhxElUrN3JR480lWhkz162yIHg65FQwulzFLoKNHkrmIy1v2a7KSzNZmVbr6A+nMI6nQNxfdsa8a/KzPLKgQi8a+GMLcobPlq1OXpY1ZXv2kx+4FaGyCnuFrc4BD8D9JO1ZqfRGJ8yDy0nxGSqTzM5a7HP/BXFW53l/99gyLGXOnr+9w0fgsN4Or8HWgGaPfoG5cx1NMQOgpbkIjhK0aywPy3j/Urrug7Jhoxp30z1I+jWo0Tlbq2Q/Dd6qhvA1+SfTDOuyrIPVN3X8jwfvurNxCPAoLlQGp9BdlxI8apa5XXIqusTLFODaYwkNGSUnsNlSxNUSX/bm+g==
    AWS_S3_SECRET_KEY: AgBQZ+dFrWmQ1TvS5AkjX2+qwBD24tokRMa5NE0gpyWueRxeXROixWpugy6taiMqq3Ezf/TCN6Ebj9aZfbQDu5O/vmrHT0tmOyFhrcMCECIGyiZhuHOlnLLcGhK2Kaj/OSuX1MKduZXbVdTKORKnn8aQrWKwOYt07tDzxHb8KDcjP8KBR/7/LWkc+9TB9vyZh36OyspfOup/dkAw5eo2kvqrUCLtAAK0QRvPGUWu//DK4CXLxblCrbA+3c/KbHcZs77p98E0jYoYnB1x7JlOksbAy30ZC1pi/oDdTnnYs2cqI6Y1fhXRdZwEI36UjVZh+1hVPCyw9dt+JA5xrvBhzogvEt8lFckqpB9I89hFALfMBdG6dlBTZrTg6W3Yfn+Gty7yws1oPFopDDGY9hM9FOEZkYAlxWOIN1rC0i9vOLvRpEpSz8ruSFb1+hrC7+arR5qCFrglZs5hD7hY81S6s/8HKi3cpr8l2pmpzpsOhbsjwjjk3NHRgWDvRPJVtwcn47f6TsX1PrjQuGFtvFMAqz1wJz4B7A2LacZallT3ALtZn87eDOv5wC17AlBuE4vS7Z7XKVmnnE5hatPClkBuPFvk4WIW+3voZ4hWWnF2RfglClrLtPi7zhdPv3QT/AR+YRxHFP5rnNqIxakxMDniztIC+hZqhhk9FxLy8a8YunFVacBsbRmhrcsaIiE/KhoBrM0qaMuTag6FfQU/b4n6bCoA+hPiuDzBC17UeiJFYxKLTbVdsGQ9PIOM
  template:
    metadata:
      name: backend-aws-secret
      namespace: tobehealthy
    type: Opaque
