---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-redis-secret
  namespace: tobehealthy
spec:
  encryptedData:
    DATA_REDIS_PASSWORD: AgAU0k6snFDV96p5lNSGWVFUUsaX3x30xgtWEIiS4bSc8H70A8+nnqdXNoVxTzaxoTAa01mDVuuusyDQM9t7EcvT97PiwD1ZCXcNhPPawp9f97CNOMC5z7ojkiK4gMTg4ZSYIHaxDzJo+sFOEp78JWhdTorHaMDHQDQUGaROjd7DxgRcajbNiSQtJ36Hf7KTzCIwSrhwzpoHnEhBar9tr7b7xJowVuwADC1ZjdsDzYWdNI4eHaYGAVQ+SHM48Ym3S2xEERUXKVZafqgcSYmOOIBk1A5aBcPH6KMbQTLyDcL1ZO6u8MDSe4PrSi9xMiseLrKV3/89vVK96x6bJle0P5tOrEaGnRFh8U+DDDNucYFamsx2OTRWMw/wQ82qq9hsgIca3jJq0DYqHayTyBikD6ILDS63Y/+Nfba0KMelXKe0+lZ6+nUlZ+944WOBGU2VnaFDIAhryOaORHIdXo3mUKCK8zR9N4xoxf8v6TyvoCaE9ZkUZOHJrldku2VqLX0mzg4KZqgqDTjeo6Nhk7JkFjSsolWwE69+KkNVV1+kOuHDViwzO0/t5jby4Lhy6GR630CbsNz9kx2nvBIjf0fdKkdBQ3wWOqAQpEi8n5TGo+vtx2M9oHVqdyV9ptIYEH6ud3f0slkvBvAhrOzCnWem8A/apv+keSxhYHSqL7vksxDxVTA4pULoIaR86K8wfgfd5rENCcMbK976YhFQgdcCjantUyu8h5Zdj+h0xLzqxVkFyw==
  template:
    metadata:
      name: backend-redis-secret
      namespace: tobehealthy
    type: Opaque
