---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-redis-secret
  namespace: tobehealthy
spec:
  encryptedData:
    DATA_REDIS_PASSWORD: AgCcytcFKV+4DtjV2tk/tq/PCN7f1XtTdVRvG2o/4fnaW23MH4z8W62saT4sPNiyl8qpVETcxMP9ujb5MumWran0drpxDgijnSySPttQAulOLefGxQrQWu3DHnHpV2yJ2uxgKZpGqICWxnxAyXreF2b7ALkDvUVXLCkQhpsoNUXbXw1kGZZAoAIq37j3J5+JEAtKlPwcfmu2K6cWukXRWPQcyBzLi6ssYok2+rWjO2qwJiusaCt24T9poMtvDiAK+p/47rztESVDJgpiLY45SccypehzpxjwRHEaWi1/TmVt9TBvMi7bdpxRAJclGCzmIXoLJ3BEC309JAvkC6YTxKLYymIYam45uaJcryAEoNkEqXznjIGv7pbAQBM4ECqRAdI5W1VNvwTP0F4ZX0uLAmCQDpJp/atVtsOBq0uqXwvv4GkxrrI8Qo4EjLIWpuIp9vfiHlODH6/OePp9UqW4mb4j1HB30C2BVflnK70CbGEifKptZczEITL58rxPA6cxuCttnckSaE1U3VSO8d4HQ3ymdqFUDv7FiRha3qrWSjoYgr581l4rQ7YqPj8T1Ul/qBQg+4iXiDxoM3LLclbFFrPZqxHc3N4gNYLxxo7oKxqNoV6YSPDuvs6m6pLvTjGh5JQNtOjzNhrVi1NBwJIwBJrxDVez1d59r3bFfbMUzRrBLwUBNeO75oSVUp7OaebvGnsoeT+vzvDzorsCmzqrKzqrvsFIwAmKNg5/VPQ3TLTZoA==
  template:
    metadata:
      name: backend-redis-secret
      namespace: tobehealthy
    type: Opaque
