---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-mail-secret
  namespace: tobehealthy
spec:
  encryptedData:
    MAIL_PASSWORD: AgBTh0Kx6gyRCpcvn1ZgjzuxZKy4DHIzytrvwmWDn9NQ2XNhyVbGt/h2XbsQ42H4zUzQ/TVWyLqff1tGXhI0JqgRXz2xvPJkTQo0yG0a2PsBQxf5Ar0q2P2x8QmTVMOc7pa9n8Ch88Q5HwMfJRtzLipHNWJd0+JU7Uq/GPYcfiVdIbsVBz6elQ/2ZRicqoN8U1ejDFmqVuwlmWRUhZC+sqbzKbx4pv3tcpG2pYEaIpIlqJ8i/W3BhXJImJl8iRsZ5r72o8ooSH+QKs/BO3FrFM/Oj4BePF9HE+nQaR79n5tMZK8KSkY2CLfO+QHXvgv0bBE/U7JU09uvL+c4GPo9ciNQ0hgi3npIj4oUcOrgsFznzUF2OM9O/IClPaWhfHK9Z5+/TatsafsxXccHIxL+XhDEfiGHDRnkGO2He89OLJCxug6aQuex5PS7nMUO7Z/pxyxkAhqryvDwQ/X2FJIU0d+WYftpbemDQ5Sdijh3zhUZxzLFIcysAPZVYaprtCk7z78jmsh+pDTLcC8D79aDlGZkgb6Iqc2WE8LylAynuftp/jQiQ6J5kAc9pCIVnPqePCdsl9l0Sc6TrsKO/14STwp4EYgIX3q0wL4Z/WGyVCUlEZhwA8B499kxOJshZlwRD1rf36PhYCO7rRqyX7tibad0b7EZfjlGD/jvET12lN1gvImj7vHjtgPQtcqxSQBPzk47w1BkenUCFr2tiqyC7QlL
    MAIL_USERNAME: AgAEfbD0KCzOFVY25Ix5FIzMynv8qZuu4NSZcX9pZ+CO5hPs+f5JU7AOo+Kfh93US/kwqc3tl9NpcJWZCeA8eZUD5fnni8CghAmEMu7ms0dB1KYI6X4Xlcv1a+q6s7rSkmLZf272tY8Yqhz0i77tiFPvtZvdabedsCm03aKlOmPBNitjuumV0SCkRaO3geXVIKugJptaNhzAQlDG9DuqtQMv+CRol9HATlr8T3qTKvU+/VihKPG8u4r3qc/K7UwXNIQGytU5HNKH1APFWb9PfX1a7Kx3G3iTSOKdUr8uxg0kZfjngHNptC2xs4b44WqqsBtTIuVmTEplvSmr6MfbB/w2ty69tgVsgj34U0wWr22ZcnWA8AIrgk18cDx1PBE0qtmhrbQMOJ+lnRRI0w9ro3ov7q2wBn1LKICzUJPtiYXiIZwDCcb6T3KhqvmwVrlNJQ9dDrVBNtWAABqyQJmSqDD7wcbe8ZDLTKierT5BDkScNWmCSlK55Kgd0ab+gO9NbJIDd1osFRsLNDEPg9WN+17rKK/ChgsCUQKhNugPofwAE4BHtjhiTVmYYqvD6nuIPAua7EhbYyKnl3uGKo+uFC/bs/iu87mmAvOf47430DvUS0H90aOD9FFJFJ3bYh7zn/oiVTXA7WGqxLJ+aHTtjpDLyNbRTatS03mptos5LjPOa4yan6rNDp65vpPN74mhtrt58AC0MJk8U/NqD8g7Yyc=
  template:
    metadata:
      name: backend-mail-secret
      namespace: tobehealthy
    type: Opaque
