---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-apple-key
  namespace: tobehealthy
spec:
  encryptedData:
    AuthKey_YAFMRF359Z.p8: AgB6CwggZv5zcKMBmE2CmJwvVNVDROie3ODJG5vXb1SEZW8Jib45ZBYYbPhWzM6CVDybnIBORu5cK+nwibSlB9PW3BIcvA+4KgZoRAplhKv5gPv7bDSUioQu6Ooh5uHUYo2h0pXDl1MFYDjW1O8Ih31Zy8Qqvoa572dx36ZFJqgE44jSqTG8+RWmUMQL43s1BOnf01OaB28K8n2g5nVDXEEZHyzBdWhx/MiNjMCeI+yXDZhxGvVwh/79eK9V/JbaRUvVKMiDeuk/nh8NjZjTv6tqRvv3xu+Vh8oJ8pMXUbzVs8SanYR1HnBecuQY+K4R2wJ57/Wokf4CpE7uEjEyTewtyd7IaNxMdMD1u6csa77eLZiKnn9vVR3qdj7bJbF+SRqwIQ+FsCqRKiihKEgbPDyWmN/flOm1JyC/A48K1rI/AXVeJnc4OryVzznqA3xLf2U+lvEAXbxr5VloKG9N6LhgyOxQ9ZS7hbJRxtJ/JYt+pm/xK+cwE7fnKs3yxpTtOocIhOrE4G5PTC7cTqFW8C4ktTqLHJCtVTGtGQeRm/F4k7047F7g2ac2Olu5N+Sofof81Xug0sjpVWSIXOiAcp8VbcmchGQRxau95UWCwbU6wdLlpy35IVOHjOT6y++AKoxbZLKckCyq2468GA5NdhKCE2CaozGljAp2hjNZckhEfC1u9qqF2rfM3nF6mYbHHpUxJvZmrkFkve2L/a19s5R8fSWY1Pd8R4tp4JctAPlr/93+6INxBZwTyICItdkpB/65pwqxK5Qxj5wjgdLLhILWLsOc1q7zCXoOx8eVE5MsK9Q5eYZdFQD1Qjx8ytCpUdDFL61SQn5IXKfOJF4iL3M8zJsN7j3Gtvgt1iJEmKbM69M8fWEmo/xMymPK9p/R4EOtgjtVkk0vlEXRQEmcHp/NT4a9VSTk8bNUSsmsIZ7Oh3TTGTZNDgWpwZDlzj/d1DpNNvJ9GrFFxCAr3dd8KCj/Dgv0dipaCTyA9p6n+eIPes+XnPl7nSj30IRsWjo9iJClECOzumc+r1QbSRpxh684eg==
  template:
    metadata:
      name: backend-apple-key
      namespace: tobehealthy
