---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-mail-secret
  namespace: tobehealthy
spec:
  encryptedData:
    MAIL_PASSWORD: AgB5K0nOGAFi2W/o8VGEMI6Vy4j743sXVWfuYEevTLsHAtcvXU/oUX2NWawgyU3/AMG6BZH/zxUdke8Ju0qkqxuG2LyjL4SuQG/Y+OrO0UVpDEAUh5FP3/eFggKxTd33fYoA4ZqGhqFA0cBjNYuZxL5vddMht2uqWkwc2r26hjWOJ94tl1QuhnwSXOTAqS1IPeOelN3NWqJx7YwkyAG4xHUJ+iW8V/x+fTacQ3Y+Jo6lK7x7rfJ4ul5n6900LQp/VVA+Qq3MpOkCl+XgsIiY30RrAylChJimjtwvHTSCHOuwVuBSo5i2AzXRhaHHcs2YWOOmcAt2p/GoePNmxDxjpXa/sULLLhNa1gvdgPcfrl/MN7MpiDQ8Xls1abdw9j5n5boq+9st4VTkuXw/hkfuNWjqTCsPfZueQQJKAuPKF1PHUdU/SKP1bLmucaKelTqVDPLfD711PcwbF6BZk4NN+0WV9RC53Yt7RRZ/CWq+6b7al80Cw1bLn7h7iryGJcfoAetOb/GHyD7slx5HgUHwowWj1KmUOKyk185wE5+L/pSce3x2Fv4hiZymGSV9tV2Sb0Hd7TFtTbWLlC5FnmKxk/1xVg+C74ut0U75glGStSR2SeyPlVoCiocAzHxZBV9wIjLimWHqkegQ3qtczCXEZLxPa3kr7JVPgILMQN/FkOLF80xyl9CSuPGfkcdLbKosOkvn6Q+1zhj49mt4pUNGpfYs
    MAIL_USERNAME: AgAqmnNTY80Nm7cxPqJx9vP1KctMCAT2mUtSPjnL/nPpk2w5vsU6ehztFK3EXVJNvVwLkdK8WAnoz5p7LZLgBbnhdzixlDPNR4GqklztZhGtkEbotAz4VTYp/7AkRPvJGZ1X87DDtoySxOzHXT2xuDJCPcfeRN5eq/EeCtH7+oETQ/gtqEmp+byGnptXLNYWJJl7kPYTdtrHJFxhAZZPjeG3gv/jLw28C6gym3j3dxsyZR3KxFW+NvechOfyBxOOuNl7JEQkLFDAAd8XEfVVHALmAbL/ONUXajaTAG7xJH3tR0ntXSdne+C2VGiQqpccuBJ5hGnYh+kaF736WvgD3mfunN/OXdu7a1FyVDtnIDOViMKdEaw7GpSKWy63uCIC7UCpZ9h2N09ygw2t1EnpH2cewoexc+YqBl/lT2MUUpKT1RJnxaqe8NX0j5Xc28s+DCGJ5qe3naU4JVL2rjKGGv+rTl2gkJgYiZqOnTHPLwyJegpLnst1oQ99xAqfVGeVw+A2j2tYvz9prmi4rDLbO7Zj1US7z/dP2K1n3t9ln8Xy8coJ/GIRRvMtFTjTOQgI39Tq+5gb1rh1cQXuTCGNUGxvAuzCKCa73UMz5T67Tvh9KKzDaOwdIdFw8sZfnG8zZi3YT3P6765wZYf4g+v/FHf7BKXgxkII7huHpmYJv4bwrVdjrHxDZfFoFNRBYpAJk05aYGoSTAzwJF5YiAO55Mo=
  template:
    metadata:
      name: backend-mail-secret
      namespace: tobehealthy
    type: Opaque
