---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-aws-secret
  namespace: tobehealthy
spec:
  encryptedData:
    AWS_S3_ACCESS_KEY: AgCTV4xWC30ggf6/q8lnldyorsVtxXs2q4hq61XRb8dxUpgD3Sj8xC2BUrohGV3lCIJDc+0WTFxD68pLDmcQn9TV+ACF10Jl8AeuLRqkZBwTHXrglCxLh9e9CEaZ7AAqbQZoR68nEA7zVKSa2wnUCxyzAF3aQoMH4twV+fLhloIekLOZ8MRe93WrQG2pvaMTDWT+DSI4txckjqNwwCkc7AcbF0c9vq8vR+9Ac1r4XLHAKmPgiBZ9NV/lyvvhfFN5A0kkZ8JxbXO3K4gOJaOkpyDAMMN7jz6DWrbGRvUdMSA7U9v9s/FYEIs14ZQtWmY2IrxVdYNffh3ArG8GoWcl8v9wmMe40dcIrMtlNEzbATihzIEQdvmE2eTy95Hu0JDDZirf/g1mZNhs38Ag/h8/HKBTGV7Ip7HXE3sg2QxOv+quKkzZkNO/Eml/dU6kjyPcM010wdzd24Dibrxt7Ec43IloqKGJLFHVO+YUH0o2MXZArsOX5q6QpRFqLZNnD/K8c3x8vtAtzZ/2WrR9qknYc8ICkP/dmGmAGKoCNPMbXxu0DQeDFbmon4Cnp84mwVFDA3xktQTbYdZhUIAXkmjv1r+j0HMGP46q3v5+6U66X/MdJjS9tXYp1OUWH6ETyXvCYvEdA+TQkpnM7FjE3xZfftPb261O6BriO/o8eQzBHUf2/0Cul6LM+rcbBBupnctdgUiTcO8vNaFeaxW873pghcX/XLo+Lg==
    AWS_S3_SECRET_KEY: AgAKpP39xQro8CjIohgoBs2B4UsDqQ1i2dS5J53fCiNnMUlAgvLfD7WMjZifCF9/ReTu3nM3xmLWoruf+7oYiUIObR6I2HDKEESjBxrfKPHj+/gp8BoP+v01/ObPtY07KLDViWMFmbIMFqQv8Jjz7UTrgxDDN9ajeWGlBUFBI/2d1KCu00vMg2qBrzA2SRCQSjorEtBFFW2oMa4jX7lZ4rFI++NXfPpUv7WdQA5cnpvxReRZhxaLXug2kPNiITL9vberKX1cqXU7n7kOcVzuj6vaeYClHmxUmwiDGsXfTkkO1zl43ciBIEPdZGdHSVYYCoA7gh11xBzlwVITa9Nhic/KX12a12xNHQmFkzPqhqmpkdB0ZMvrUfrnFPC6yvGq9Uxs0Tz6s98guiMdsdkpLlmI8bICHocu0VYJVCwUt7IP8JLS0sSDJ29y3y7nzwML6oBoozTXwuxHeXgthKeIAY7Dm1WOmKitslXLsOCI5jIUxDqxeALcwKtCo4xA4GINdYEXjuwQDk2/Irfkgljv8qFqSRAOSnKptk9lPEBGLjP+IK6cRvNFg1aqxJ4UP5nrof4uGp8nr3wSQ6oJU0PI3MAAliQ+/OHFo4QtkEnca1i5ZklCFqxFxdLSH8hEY1sF32aTqVistJRRaoZgvGfTcq1Urp0XvhFtH/wxUIrNnCLXn9EF8feGjY251ovDCMQoeYYMAm4x+SrT1W76uY9O7l+9K3uFzw+z5CKjUl5oxX7mU2keAfdYm0Aw
  template:
    metadata:
      name: backend-aws-secret
      namespace: tobehealthy
    type: Opaque
