---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-jwt-secret
  namespace: tobehealthy
spec:
  encryptedData:
    JWT_SECRET_TOKEN: AgCH/sLoD5D1/QDd09BnRfEpquA4bVtiHXgf1CxJDQGieEOX36oYhtsXIWSbaTTkukazVfQAbuFvzIDUCJdq6+7G4nr1dMMtfnlwYRkZ4rDwBlIruOcOPTnnAJcSl+3dovH+thRjiSqi0hbyTaAJV17Q+bUJuLdUHgMhZ2/VzdrXNfIVw/Cbmgj/g85qv3fTbcNfMrNQL2cWqaY2LuIGrUQxTB58veBAxB/SYwhGBFr413RdGgOdCDPtF3bByZNEu/pgHPEtqURGosm95r/e1i+f9BxF5QeHP4z6WEhc07CCR/BkofIK+Nk7z4DwdXLWdb2pNhjLYfh+N43yi1ZPxi++OhiMdVwO10+DFpboMZZw39yeXvtZSee5CjbL3Jp1wzAItbKm1kb88S+bx9jMLmgCNbn9vtICBdMMiL0XamYwZs6NrxceIrRh16q8H9rIBsO1xkDyAUnINWTzrmukKvzjdFz4sVBzJNlaarZGOAFvB2tL58h2LFi2/tHoThMhtyuG0Fp5RSvqA/qW7CgDn6VHoqevw5S4MFU/1Ymm+0cvRgxu5SfardAci5dPkLkkPPxPlnXce+xjgPAuX9q4D07HztfqR1dfGdgwmz9SXpRPBNhlnVZJrRk7Pgdw0g8zxuXGWKjT4E2vLuJb59qSdlwIutQuRWIi4QO50xzcsYNBwGDdxzxW6AYC8IC3eIfSCsRk5axZy1eCrRJZgaU3hHBkvB+WWhArfJmKpiXwInbrnBD6iAVprFciwxhVceaHTF6QoZUs1+HPHnygfvUojJ9p
  template:
    metadata:
      name: backend-jwt-secret
      namespace: tobehealthy
    type: Opaque
