---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-jwt-secret
  namespace: tobehealthy
spec:
  encryptedData:
    JWT_SECRET_TOKEN: AgCYE+vcBxlyUywLHLWi37J3JcfGQC3DKedUIt7lMuqfIYUecrnU6DFpEk6/qQSjXq0eyvGhJHsODngRyKSEYs38qkN9c41/n0W4aTKZnNMJxDhDJ6oHO1dxztM1Jv8hWxtmoHcYhsadGp0EqCpk3zuUZJFDn4RFmBAm6EcgaJUItN7r3tbGJLDXnhw4WzMWbrZBDorNWkaTx4e17XbolYW9rGuSxvSdsJiuZ8u537DGuZmEzZg1BM/ySA3hqLXxRCsqtdBXLzst9EsBYgm5Tfn4xWNExoP7/Y0ZZuTkJtKAZl3hzoBpVPxUcaSepYYQRZakmoDtVs2eAvaDHBSThG8DpxOlk6eJN79pY4fqYlW9YBr3f3p71ZattZske/7qkWhhzO7WQhmip4yciFF47zDotvYj3n+AbAa4NpJPezynZBk/+yjxLDaIdFG+gUY6Op7dIb4RAdEUW48COfO0OmkcKQjDw8jFc1IUNd9udb/1XO28Q4rhVh9wxk6ziNiFnuRUUJYgQwGylA6BaTiRcmuVgQ+xw0dtQ7EfdnyjtFWg5bfEtb1wRE/7ObtnKyQcGDkeHb0e4hnyRNDw3hZaNu49Mtlh7I33S2EIixYd3FyrbGGuHaNu+IjKLQ0Fcsd0OjVCIeS1WeaMt9CClwEdtzKjxPLz2lIk7u7AV4se4rqu/IFLdj41PdJ1At/YyVUVpHqP45KC0vIsfEg7uB4t8RKyVyHNcbfvaSv9YT2C6483PR3e+xf3h2VsL0ygefL5wX/7T9xk3bO/Zxe55hbfoW2+
  template:
    metadata:
      name: backend-jwt-secret
      namespace: tobehealthy
    type: Opaque
