---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-env
  namespace: tobehealthy
spec:
  encryptedData:
    INTERNAL_API_URL: AgAxpHcagBXmd0kGPnpt5S0ixUZkeyl0QAu5xBdTJ9DRRssdoXxnsnTxkSWSwZruqZCdVYv4bLCTsAW447DdpMzoupwSaMlJHGV39kigl9rm/4YII7nd64NML+e1qCxzXv7Fnh5uJbyyL80uofxHi9C5O3aeQWA1HugTwkztNDx9/9A2qjcIBt32QZ68Oq6j98NNJ4X9rbhpnaDsKUI1VWi7DC4pkq6mg3LFFPp2aFJakQHIfost2BWJyFAm2eYvIlIbNG8+2Ay0E6DiUY1hSjh5i2eeTpu1mfS08vxvhgUFEzSJC3MJDxgqaEBp0rVIBjflFyLUFLE4qhJ0qnhRbsEGTIUha+coOtKJNre8bcgGi7P5XLdMeLE570D5rjfqEmswH8fHwXKFZFTC+7NO3zXDcGF1YzSS5VipT/AzLbxQYYK13RCdUZiYUtadWzKj4DhjhvlQn6FXyd1trrObFULLEDcsBE+Ke/IpwOWki4isqBXKxhf3W1UUuFHVR+UurSm1/Ao0PwPy76ufr+ncz6MkVrV4TDGs7Mx4tXQgMZAQkr+GU4vIxgW5osqt+2fe0HRh4Ua5HFvlAP9xkFBEK6mxZqWbWRPKcupMMxqYV8j3zPXthxwo2W5UfD8xZHZ7IMy33z0sYDRqJmkDLWR+bqZvqGzXNXaWav0CEA9/eZCVAti3DiYlr9GJBf0xP23EOA12aTEfo5ANpaNOoh3YuLuNRqY1
  template:
    metadata:
      name: frontend-env
      namespace: tobehealthy
    type: Opaque
