---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: tobehealthy
spec:
  encryptedData:
    .dockerconfigjson: AgALNA+n85sSD26FaCK7zk6LQmmwspnMmjt89eVD2XmVWpLpG2Ylf5zqOygyqGR2w/zz4zd9mEshvNMLRObXq+PySqeodYboE9+H5wn8xa3wIGgNRPiwdaDrHJTbb8kYIfWPtC4Opk/TwAxiSm98NWK6sw+eQvnQR2xwMyqzEs5uI2Uf/RTEGnwIlABiiZnRs5vcFm17BxqnFXr4yo8DO743BU9Sx61j7Osk/ptRirvyMrY9nXdTzkyP2WmaNCuy1sH1LbJTSH7KQkCScLfbCKqpuw/J7m2/8R8slrLVSwgLE7RBIDDLj0V+0xmvxWEpmjKcWoCKMZZIm/ONYCKmxK5PW3xcjWaA/Qu0IZfgf9hZ9pdrhNqAWS6dsr4agotsSKNeAcSdhF7lTJL/F6yd1J3DtfKlE5iBfr0w+ctU1/WkD1rQXM7t8algVfjjalr2uHF0tnD2MvxMsgqBPe4E8JelbdFdlHpJndo1Q7aKr5YHz/Pi8cZLaV14p8u8EZXIP8MvH2nYcGNbuSg9hTVSpXtNYOcgjki0WsNOOzQgN54IptjVqCw19YlDS5JNHfTRQ7Hp0RWqk7ZxvF+gCX/suBQBgPfFHLkhXbsnxgZ6lamEWj412twAAijXiAijkGccR5C34LZnYo9wOSNsTKuemczB4fvYOqNQKEut8XWjyXh72VixhUWt6lScgOQ7hBjKsaNDo0FB3YV7YCcYWl+FyWUhxk3e319JVmaXj7bXGvYYdg6A17eHDnEfvyYKu7zlB4NjMRAq73oxwZJ4hNUzl9/EXzea/1kDwb166rlDcj433Y/VjFpN/fynoI0m2+/bfnd2bU39ZDL6UEyRd1eB/a0admYARSZtWM5a1kt7vwwpeMY9yGut7xfIVV2+Xq+eSOGUjBZAuzqW+DmOA4/iA2f9baGLrI5Jr66hPWJVgg/0js5zdhyLuA8MTw==
  template:
    metadata:
      name: ghcr-pull
      namespace: tobehealthy
    type: kubernetes.io/dockerconfigjson
