---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: tobehealthy
spec:
  encryptedData:
    REDIS_PASSWORD: AgB48+ggrcXidpMguwQQhOeGBeFykYixXLTWwPE6aLemN+5bXgmB5GoLgJs3MCPD4j9F4KlWDIG8fdFUgVNft8k6pMj/CE9IHIc3RapvqnyGItbeUnlcn2ose2CiVZG/F0kj44sFU3ykE4ifnW3tUygMg5DKLqy3r3CROM8Tr1lXOkODWlftAzd7bscTofK1Z2jZChKZYeDabrnnwZW+0JRxtX+Gijd5Hm1tILhhTyF7EOgY6KT0VC25A6VsvEwOs7eY4QfyC4OoPKNzcfW+5n58ry31BhvFYlYcZp2NbbwlfHBj9yXkZ3lmqNdspU6ha6pEh8NWOGz77nEjDBoy26sCUabIOiKc941Px42YaPsCgllpNFj9KJ1HoS4Y//nlOW7hac58AlK/5BbJ9X75CwmR4gG37rPEtVeyUPdcakWINxlj15AIGhiCs6ezVb5B+GFstY604FuoQ4beVObJ42K4u5tAjHPUuv9webuu5aMvyD+Dn54Q+kwEuyVp6dHRDKj6Ai0LbEbWVm3SLAqFJoejQ3i1LjQEeznFG8ZSpQ8g107qXuqYAUYtfq5ka9myMao2iPOGEZ4j1dlTMZgTaGIo736/6xICpiJpBf4YJc3hntL0MVcq2FlmHuoXbfKRFldxetGYL9/Rb1PEN5jUEvYcupO+RqGeRZN11KBxXtyHHCA81gIXqRmboixQtP+jk8nj1xvUKPYg/GO/j7SBAe8BiIrOiWxoEHpI0088kQdbOg==
  template:
    metadata:
      name: redis-credentials
      namespace: tobehealthy
    type: Opaque
