apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tobehealthy-dev

resources:
  - ../../base
  - secrets/db-credentials.sealed.yaml
  - secrets/redis-credentials.sealed.yaml
  - secrets/backend-env.sealed.yaml
  - secrets/frontend-env.sealed.yaml
  - secrets/ghcr-pull.sealed.yaml

images:
  - name: ghcr.io/to-be-healthy/backend
    newName: ghcr.io/to-be-healthy/backend
    newTag: sha-e59c86623365
  - name: ghcr.io/to-be-healthy/frontend
    newName: ghcr.io/to-be-healthy/frontend
    newTag: sha-fba4ea736b87

patches:
  - target:
      kind: Ingress
      name: tobehealthy
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: tobehealthy
  - target:
      kind: Ingress
      name: tobehealthy-www-redirect
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: tobehealthy-www-redirect
  - target:
      kind: StatefulSet
      name: mysql
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 2Gi
  - target:
      kind: PersistentVolumeClaim
      name: backend-files
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi
