---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-env
  namespace: tobehealthy-dev
spec:
  encryptedData:
    INTERNAL_API_URL: AgA2XdzSVGax69BCzuroOs2onzSVyq5UjtL/Z8elzRcR6Pii89jp14cYGvryogpmfZH8Qz+gMOjiSVF4JmF6Tpd+O0LzXLes91s6kZ6xdSzGLyCRRPEJanN7pSXF0AOTpXt+wbrTDuS4j0zpxEc2hP7GPJWffADmpO+mUyNMw0zQTQ7rb6/8CiG6z4AA52XDoOpJIT5he9JA+zlKobgoFwUCKAS5Oc6WRugppl359Ywzh+C6S9z/oK58oOgP+uHdzfuISs5ForCcIPLHgKWmUK1pawGi8XqkKtMz9M96CxYubiLeJ9E9rq4YVoxo1qY1XFEmMb9EPtBtU1Ign/jnHgB5h5tVkNjCQ6IdZgelQ2E8mi6UKZYBxhDkCYwLTg+JUY6q9WrkDCzA/fpDqG8S64IduaMHCBW8fVZoPpiltg9SUFAVa+ppeVuVJDYmOhJ+1IOX/4Is4vGlN+PuWZjyT711AlFtc7OKe0S090jzmlpYxdbhGY+cahq47nzh4MNN4kPvbNidwpUZ9s1QcvH1ox9Lq4pNF+o2MFvEdZ9lqosTDjfmhzHVp5r5H8Q1HLDLmK0U5RPAxtw7I1ezQIgE5GpMTewDvJCTDrCC59HY1oWO8vOrob88f7XRpKRimL//pFxA0rwZ8+7Utg+lt1CybOo3zHGPmEbs7bJhScsg8C1mhZfYnEkKLEaZ6zJ7l5LdfyTeXeqYGS1wg4IcE9FpPP5GR+66
  template:
    metadata:
      name: frontend-env
      namespace: tobehealthy-dev
    type: Opaque
