---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: tobehealthy-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCVLqhvqRuxEzeIHfGxWlcgdYY+mxo1FZ6+X9diCuCF5oFsYbzMtlGHJ13ojMwHx+SoSg9pO6RU1UWwETjZohFF6L/Oai2ce9UbHKYoGc9A5JdnDDnXjkDdFubwzpfpxTlZLcb4Imk7WaewbdntCQ77nVsIJBo6pyoOn6hpvx25dKdMrBUaLfRDZohRM4cdo2WLgTpWs8hxE+ce90I6bjfxQOkLFYuLB/6PpG3scEYuxNsImzYynESN/qd1NhmRfU0urfUmiT6TWmrXeDz/20Z4LFrx1C26N0F4pAs/1x4NYnReTk7C/TgOmEh2OyZz5og0/E9BHxT7LgPLvQEPv1uFrDb9UsnGFmcB/0OGK/DncxNFT0x9jkuFJIk4PFqQZlWz+aRPDjvirhNaMdHqoCInaLbZgtM1WidPzHKKAVRIEzNum5ke4+i8dmvNzIZb7nL97IDDcmQ1T3NsZSttujN14y81HsHtwSxVAqgJLqQgLXTnaKNq6S9tBs12ZHyL5TRnn1UYCdRvz+54uRvd32dd1IrDgYaGjgrPF6Aj6ID3h6G8WkwqlbH2nNVpXQTY9R/+TuT7v+rqmJ4ARw5SYcJO4Pyr2S5Izd3ZGHVVvJhjNF5iX6qvHhLmctQ2IyzTAo8UkZSGPod4rRuZg/wSONShpyahqDN6Tf6Y7fJGvQ/pnj5Erwu3sX97vBLMgbRVn8vTq9BoVa86YkmYjqVbmQw3Viq5qjEVp1bU7T7jdPtvx7LqMhvYjkB/HHp1bVYTrpwQb1XHRVCz7mNbn9ssRyQTeruequQwtzZutTgTeCu9+z5sB0CrjV3PSBzOd7A7PcZaeGWFdPHIwUGO17smUf1Cqf0/iyDve+IDlamM8gzkm5howbBx6uMjUoVHbPzNrlYAIavmiBHVVVDvoRjqJidQK3w/yi/icP6MJQwFSsdhrEwvgosgXUH1mg==
  template:
    metadata:
      name: ghcr-pull
      namespace: tobehealthy-dev
    type: kubernetes.io/dockerconfigjson
