---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: tobehealthy-dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgBbegKpaSBKPg5yan/Eft8JbEc9OzItGfhh5vOC5LGyhhhJZRdyGhwKAOSIqzk1nZmQ/7Qz8eRu2hPdVqK7y7X3EvkOEAOPzojmSawrEIdn3gmy4Qoqar/p1A6TBh5Og8lUR4NeB0C2du6Q2S2mr64yBUp3eQPILaImwws6stEfXe4SR7cqy8cAWuEP0fBJn2yT1Mxdlh3tpu20CSc6PZLMPMhmMp5gwPl68xqmOmJ1VSBK/WphZkQIwI2sSReAVzNsBF/5zYrfnit2eu1p6R4aX6gZzgM0WWc+vC4spzazJeC9CsmdSu5nmbFF5B1G+iGxVWRKUWdLfrGxNd2TvXXl4gXC8GwgznHCbOE6EEc2MAyZjSQdbt6TaNPY4vZ/kouuJZbb152Hlg7S6VpXbk3I89Zgrwb65loCQcB3BZMoYdD93CWykc+ueRNLjUvgvPqa9tf9Vo5dLaciyeIqSFl254+EjpRu2JVHfTfzsSMNTAIGZ2gODkVvOtjLcdC8hBS71AOPn9/j7tbo33VxbeKSC1vp/e1NCaBXOCZ0DsSJMwUjzY7sqGPOvKUXrn9kKTR+zVF+Xjd0pIWy+EWZa1QrBYI6lrMrkBx0mPYJXhG4ChkQEtG2MsJ5YXnGNwwSidThTErXwh4e6Ih6wAbb8Jg2KPWCKZ9dA78uDRyPtiWTUkFPw/6EQgd1S6SdtVKiR8BmkIslDimdyRvNysG5nMMhOiRW1zV8l9CB+2mjomHNqA==
  template:
    metadata:
      name: redis-credentials
      namespace: tobehealthy-dev
    type: Opaque
