apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: malitda

resources:
  - ../../base
  - secrets/malitda-azure.sealed.yaml
  - secrets/malitda-gemini.sealed.yaml
  - secrets/malitda-postgres.sealed.yaml
