apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tobehealthy

resources:
- https://raw.githubusercontent.com/to-be-healthy/frontend/develop/deployment.yaml
- service.yaml

images:
- name: ghcr.io/to-be-healthy/frontend
  newName: ghcr.io/to-be-healthy/frontend
  newTag: sha-151faa1dd497
