apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tobehealthy

resources:
  - ../../base
  - secrets/db-credentials.sealed.yaml
  - secrets/redis-credentials.sealed.yaml
  - secrets/backend-env.sealed.yaml
  - secrets/frontend-env.sealed.yaml
  - secrets/ghcr-pull.sealed.yaml
