apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tobehealthy

resources:
  - ../../base
  - configs/backend-config.yaml
  - secrets/db-credentials.sealed.yaml
  - secrets/redis-credentials.sealed.yaml
  - secrets/frontend-env.sealed.yaml
  - secrets/ghcr-pull.sealed.yaml
  - secrets/backend-db-secret.sealed.yaml
  - secrets/backend-redis-secret.sealed.yaml
  - secrets/backend-jwt-secret.sealed.yaml
  - secrets/backend-mail-secret.sealed.yaml
  - secrets/backend-aws-secret.sealed.yaml
  - secrets/backend-oauth-secret.sealed.yaml
  - secrets/backend-apple-key.sealed.yaml
